@startuml
left to right direction
skinparam linetype ortho

actor "Специалист ТХП" as specialist
actor "Клиент"
actor "Пользователь"
actor "Администратор"

"Пользователь" <|-- "Клиент"
"Пользователь" <|-- "Администратор"
"Пользователь" <|-- specialist

rectangle Система {
  usecase (Просмотр своих заявок)
  usecase (Выбор заявки)
  usecase (Фильтрация и сортировка заявок)
  usecase (Просмотр закрепленного оборудования)
  usecase (Создание заявки)
  usecase (Комментирование заявки)
  usecase (Просмотр информации о клиенте)
  usecase (Просмотр информации об исполнителе заявки)
  usecase (Смена статуса заявки)
  usecase (Обработка заявки)
  usecase (Отмена заявки)
  usecase (Позвонить исполнителю заявки)
  usecase (Связаться с исполнителем заявки в ТГ)
  usecase (Позвонить клиенту)
  usecase (Связаться с клиентом в ТГ)
  usecase (Авторизация и аутентификация)
  usecase (Автоматическое назначение заявки на специалиста ТХП)
  usecase (Настройка получаемых уведомлений)
  usecase (Просмотр списка пользователей)
  usecase (Создание нового пользователя)
}

rectangle СистемаУведомлений {
  usecase (Получение уведомлений о назначенных заявках)
  usecase (Отправка уведомлений специалисту ТХП)
}

Пользователь -> (Авторизация и аутентификация)

"Администратор" --> (Просмотр списка пользователей)
(Создание нового пользователя) .> (Просмотр списка пользователей) : <<extend>>

specialist --> (Позвонить клиенту)
specialist --> (Связаться с клиентом в ТГ)
(Позвонить клиенту) ..> (Просмотр информации о клиенте) : <<include>>
(Связаться с клиентом в ТГ) ..> (Просмотр информации о клиенте) : <<include>>
(Просмотр информации о клиенте) ..> (Выбор заявки) : <<include>>

specialist --> (Получение уведомлений о назначенных заявках)
specialist --> (Обработка заявки)
(Обработка заявки) ..> (Выбор заявки) : <<include>>

specialist --> (Настройка получаемых уведомлений)
(Обработка заявки) ..> (Смена статуса заявки) : <<include>>

"Клиент" -> (Связаться с исполнителем заявки в ТГ)
"Клиент" -> (Позвонить исполнителю заявки)
(Позвонить исполнителю заявки) ..> (Просмотр информации об исполнителе заявки) : <<include>>
(Связаться с исполнителем заявки в ТГ) ..> (Просмотр информации об исполнителе заявки) : <<include>>
(Просмотр информации об исполнителе заявки) ..> (Выбор заявки) : <<include>>

"Клиент" -> (Просмотр закрепленного оборудования)

"Клиент" --> (Создание заявки)
(Создание заявки) ..> (Автоматическое назначение заявки на специалиста ТХП) : <<include>>
(Автоматическое назначение заявки на специалиста ТХП) .> (Отправка уведомлений специалисту ТХП)

"Клиент" -> (Отмена заявки)
(Отмена заявки) ..> (Смена статуса заявки) : <<include>>
(Отмена заявки) ..> (Выбор заявки) : <<include>>

(Комментирование заявки) ..> (Выбор заявки) : <<extend>>
(Фильтрация и сортировка заявок) ..> (Просмотр своих заявок) : <<extend>>



@enduml