@startuml
left to right direction
skinparam linetype ortho

Клиент --> (Просмотр своих заявок)
(Выбор заявки) ..> (Просмотр своих заявок) : <<extend>>
(Фильтрация и сортировка) ..> (Просмотр своих заявок) : <<extend>>
(Комментирование) ..> (Выбор заявки) : <<extend>>
(Отмена заявки) ..> (Выбор заявки) : <<extend>>
(Позвонить специалисту ТХП) ..> (Выбор заявки) : <<extend>>
(Связаться со специалистом ТХП) ..> (Выбор заявки) : <<extend>>

Клиент --> (Просмотр закрепленного оборудования)
Клиент --> (Создание заявок)
@enduml