@startuml
left to right direction
skinparam linetype ortho

actor "Специалист ТХП" as specialist

specialist --> (Просмотр заявок)
(Выбор заявки) ..> (Просмотр заявок)  : <<extend>>
(Смена статуса заявки) ..> (Выбор заявки) : <<extend>>
(Написание комментариев) ..> (Выбор заявки) : <<extend>>
(Добавление вложений) ..> (Выбор заявки) : <<extend>>

specialist --> (Просмотр техники)
(Изменение состояния техники) .> (Просмотр техники) : <<extend>>
(Изменение владельца техники) .> (Просмотр техники) : <<extend>>

specialist --> (Просмотр ПО)
@enduml