@startuml
left to right direction
skinparam linetype ortho

actor "Специалист ТХП" as specialist

specialist -> (Просмотр заявок)
(Выбор заявки) ..> (Просмотр заявок)  : <<extend>>
(Смена статуса заявки) ..> (Выбор заявки) : <<extend>>
(Комментирование) ..> (Выбор заявки) : <<extend>>
(Просмотр информации о клиенте) ..> (Выбор заявки) : <<extend>>
(Позвонить клиенту) ..> (Просмотр информации о клиенте) : <<extend>>
(Связаться с клиентом в телеграмме) ..> (Просмотр информации о клиенте) : <<extend>>
'specialist --> (Просмотр техники)
'(Изменение состояния техники) .> (Просмотр техники) : <<extend>>
'(Изменение владельца техники) .> (Просмотр техники) : <<extend>>
'
'specialist --> (Просмотр ПО)
@enduml