@startuml
left to right direction

'Администратор -> (Просмотр списка пользователей)
'(Регистрация пользователей) ..> (Просмотр списка пользователей) : <<extend>>
'(Удаление пользователей) ..> (Просмотр списка пользователей) : <<extend>>
'(Редактирование пользователей) ..> (Просмотр списка пользователей) : <<extend>>
Администратор --> (Создание/Просмотр/Удаление/Редактирование пользователей)
Администратор --> (Создание/Просмотр/Удаление/Редактирование видов техники)
Администратор --> (Создание/Просмотр/Удаление/Редактирование категорий ПО)
Администратор --> (Создание/Просмотр/Удаление/Редактирование категорий заявок, связанных с ПО)
Администратор --> (Создание/Просмотр/Удаление/Редактирование категорий заявок, связанных с техникой)

@enduml