@startuml
'https://plantuml.com/sequence-diagram

participant Клиент
participant Сервер
database "База данных" as БД

Клиент -> Сервер: POST запрос /auth {username, password}
Сервер -> БД: Запрос данных пользователя {findByEmail(String email)}
БД -> Сервер: Получение сущности пользователя {Employee}
Сервер -> Сервер: Проверка данных и генерация JWT
Сервер -> Клиент: Возврат ответа 200 - {user, JWT} или 401 - Unauthorized
Клиент -> Сервер: HTTP запрос с заголовком Authorization = {JWT}
Сервер -> Сервер: Проверка JWT и прав пользователя
Сервер -> Клиент: Возврат ответа, сформированного по правам пользователя
@enduml