@startuml
left to right direction
skinparam linetype ortho

Клиент -> (Просмотр своих заявок)
(Выбор заявки) ..> (Просмотр своих заявок) : <<extend>>
(Написание комментариев) ..> (Выбор заявки) : <<extend>>
(Отмена заявки) ..> (Выбор заявки) : <<extend>>
(Добавление вложений) ..> (Выбор заявки) : <<extend>>

Клиент --> (Создание заявок, связанных с ПО)
(Создание заявок, связанных с ПО) .> (Просмотр ПО) : <<include>
(Создание заявок, связанных с ПО) .> (Просмотр категорий заявок, связанных с ПО) : <<include>

Клиент --> (Создание заявок, связанных с техникой)
(Создание заявок, связанных с техникой) .> (Просмотр техники) : <<include>
(Создание заявок, связанных с техникой) .> (Просмотр категорий заявок, связанных с техникой) : <<include>
Клиент ---> (Просмотр закрепленного оборудования)
(Создание заявок, связанных с техникой) .> (Просмотр закрепленного оборудования) : <<extend>>
@enduml