@startuml
left to right direction
skinparam linetype ortho

Система --> (Осуществление авторизации и аутентификации пользователей)
Система --> (Автоматическое назначение заявки на специалиста)
Система --> (Фильтрация и сортировка элементов)

@enduml