@startuml
left to right direction

skinparam linetype ortho

:Клиент:
:Специалист_ТХП:
:Администратор:
:Система:

Администратор -> (Просмотр списка пользователей)
(Добавление пользователей) ..> (Просмотр списка пользователей) : extends
(Удаление пользователей) ..> (Просмотр списка пользователей) : extends
(Редактирование пользователей) ..> (Просмотр списка пользователей) : extends

Администратор --> (Просмотр списка категорий ПО)
(Добавление категорий ПО) ..> (Просмотр списка категорий ПО) : extends
(Удаление категорий ПО) ..> (Просмотр списка категорий ПО) : extends
(Редактирование категорий ПО) ..> (Просмотр списка категорий ПО) : extends

Администратор --> (Просмотр списка видов техники)
(Добавление видов техники) ..> (Просмотр списка видов техники) : extends
(Удаление видов техники) ..> (Просмотр списка видов техники) : extends
(Редактирование видов техники) ..> (Просмотр списка видов техники) : extends

Администратор -> (Просмотр списка категорий заявок ПО)
(Добавление категорий заявок ПО) ..> (Просмотр списка категорий заявок ПО) : extends
(Удаление категорий заявок ПО) ..> (Просмотр списка категорий заявок ПО) : extends
(Редактирование категорий заявок ПО) ..> (Просмотр списка категорий заявок ПО) : extends

Администратор -> (Просмотр списка категорий заявок устройств)
(Добавление категорий заявок устройств) ..> (Просмотр списка категорий заявок устройств) : extends
(Удаление категорий заявок устройств) ..> (Просмотр списка категорий заявок устройств) : extends
(Редактирование категорий заявок устройств) ..> (Просмотр списка категорий заявок устройств) : extends


Специалист_ТХП -> (Обработка заявок)
Специалист_ТХП -> (Написание комментариев и прикладывание файлов для заявок)
Специалист_ТХП --> (Учет оборудования)
Специалист_ТХП --> (Анализ архива заявок)

Клиент -> (Написание комментариев и прикладывание файлов для заявок)
Клиент --> (Создание заявок по вопросам с техникой)
Клиент --> (Создание заявок по вопросам с ПО)
Клиент --> (Просмотр закрепленного оборудования)

Система -> (Осуществление авторизации и аутентификации пользователей)
Система --> (Автоматическое назначение заявки на специалиста)
Система --> (Фильтрация и сортировка элементов)
@enduml