@startuml
left to right direction

skinparam linetype ortho

:Клиент:
actor "Специалист ТХП" as specialist
:Администратор:
:Система:

Администратор -> (Просмотр списка пользователей)
(Добавление пользователей) ..> (Просмотр списка пользователей) : <<extend>>
(Удаление пользователей) ..> (Просмотр списка пользователей) : <<extend>>
(Редактирование пользователей) ..> (Просмотр списка пользователей) : <<extend>>

Администратор --> (Просмотр списка категорий ПО)
(Добавление категорий ПО) ..> (Просмотр списка категорий ПО) : <<extend>>
(Удаление категорий ПО) ..> (Просмотр списка категорий ПО) : <<extend>>
(Редактирование категорий ПО) ..> (Просмотр списка категорий ПО) : <<extend>>

Администратор --> (Просмотр списка видов техники)
(Добавление видов техники) ..> (Просмотр списка видов техники) : <<extend>>
(Удаление видов техники) ..> (Просмотр списка видов техники) : <<extend>>
(Редактирование видов техники) ..> (Просмотр списка видов техники) : <<extend>>

Администратор -> (Просмотр списка категорий заявок, связанных с ПО)
(Добавление категорий заявок, связанных с ПО) ..> (Просмотр списка категорий заявок, связанных с ПО) : <<extend>>
(Удаление категорий заявок, связанных с ПО) ..> (Просмотр списка категорий заявок, связанных с ПО) : <<extend>>
(Редактирование категорий заявок, связанных с ПО) ..> (Просмотр списка категорий заявок, связанных с ПО) : <<extend>>

Администратор -> (Просмотр списка категорий заявок, связанных с техникой)
(Добавление категорий заявок, связанных с техникой) ..> (Просмотр списка категорий заявок, связанных с техникой) : <<extend>>
(Удаление категорий заявок, связанных с техникой) ..> (Просмотр списка категорий заявок, связанных с техникой) : <<extend>>
(Редактирование категорий заявок, связанных с техникой) ..> (Просмотр списка категорий заявок, связанных с техникой) : <<extend>>

specialist ---> (Просмотр списка заявок)
(Выбор заявки) .> (Просмотр списка заявок)  : <<extend>>
(Смена статуса заявки) .> (Выбор заявки) : <<extend>>
(Написание комментариев) ..> (Выбор заявки) : <<extend>>
(Добавление вложений) ..> (Выбор заявки) : <<extend>>

specialist---> (Просмотр списка техники)
(Изменение состояния техники) .> (Просмотр списка техники) : <<extend>>
(Изменение владельца техники) .> (Просмотр списка техники) : <<extend>>

specialist---> (Просмотр списка ПО)

Клиент ---> (Просмотр списка своих заявок)
(Выбор своей заявки) .> (Просмотр списка своих заявок) : <<extend>>
(Написание комментариев) .> (Выбор своей заявки) : <<extend>>
(Отмена своей заявки) .> (Выбор своей заявки) : <<extend>>
(Добавление вложений) ..> (Выбор своей заявки) : <<extend>>
Клиент --> (Создание заявок, связанных с техникой)
(Создание заявок, связанных с техникой) .> (Просмотр списка техники) : <<include>
(Создание заявок, связанных с техникой) .> (Просмотр списка категорий заявок, связанных с техникой) : <<include>
Клиент --> (Создание заявок, связанных с ПО)
(Создание заявок, связанных с ПО) .> (Просмотр списка ПО) : <<include>
(Создание заявок, связанных с ПО) .> (Просмотр списка категорий заявок, связанных с ПО) : <<include>
Клиент --> (Просмотр закрепленного оборудования)

Система -> (Осуществление авторизации и аутентификации пользователей)
Система --> (Автоматическое назначение заявки на специалиста)
Система --> (Фильтрация и сортировка элементов)
@enduml