@startuml
left to right direction
:Клиент:
:Специалист_ТХП:
:Администратор:
:Система:

Администратор --> (Добавление/удаление/редактирование пользователя)
Администратор --> (Добавление/удаление/редактирование категорий ПО)
Администратор --> (Добавление/удаление/редактирование видов техники)

Специалист_ТХП -> (Обработка заявок)
Специалист_ТХП -> (Написание комментариев и прикладывание файлов для заявок)
Специалист_ТХП --> (Учет оборудования)
Специалист_ТХП --> (Анализ архива заявок)

Клиент -> (Написание комментариев и прикладывание файлов для заявок)
Клиент --> (Создание заявок по вопросам с техникой)
Клиент --> (Создание заявок по вопросам с ПО)
Клиент --> (Просмотр закрепленного оборудования)

Система -> (Осуществление авторизации и аутентификации пользователей)
Система --> (Автоматическое назначение заявки на специалиста)
Система --> (Фильтрация и сортировка элементов)
@enduml